"""Phase-2 generic CORS verification package (no Horizon hardcodes)."""

from __future__ import annotations

from verifiers.cors.adapter import CorsVerifier
from verifiers.cors.contract import (
    STATE_BROWSER_READ_BLOCKED,
    STATE_CONFIRMATION_UNAVAILABLE,
    STATE_CORS_BROWSER_READ_CONFIRMED,
    STATE_INCONCLUSIVE,
    STATE_NEGATIVE,
    STATE_PASSIVE_HEADER_OBSERVED,
    STATE_REFLECTED_ORIGIN_WITHOUT_SENSITIVE_READ,
    STATE_UNCREDENTIALED_PUBLIC_READ,
)

__all__ = [
    "CorsVerifier",
    "STATE_CORS_BROWSER_READ_CONFIRMED",
    "STATE_PASSIVE_HEADER_OBSERVED",
    "STATE_BROWSER_READ_BLOCKED",
    "STATE_UNCREDENTIALED_PUBLIC_READ",
    "STATE_REFLECTED_ORIGIN_WITHOUT_SENSITIVE_READ",
    "STATE_CONFIRMATION_UNAVAILABLE",
    "STATE_NEGATIVE",
    "STATE_INCONCLUSIVE",
]
